import Database from 'better-sqlite3'; import fs from 'node:fs'; import path from 'node:path'; import { defaults, type Settings, type ScanResult } from './types';
// Docker sets CONFIG_DIR=/config. A project-local fallback keeps clean-checkout builds and tests write-safe.
const dir=process.env.CONFIG_DIR || path.join(process.cwd(),'config'); if (!fs.existsSync(/*turbopackIgnore: true*/ dir)) fs.mkdirSync(dir,{recursive:true}); const db=new Database(path.join(dir,'media-guard.db')); db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1), data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS scans(id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL, fingerprint TEXT, decision TEXT NOT NULL, reason TEXT NOT NULL, data TEXT NOT NULL, scanned_at TEXT NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS scans_fingerprint ON scans(fingerprint); CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS rejections(identity TEXT PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);`);
export async function getSettings():Promise<Settings>{ const row=db.prepare('SELECT data FROM settings WHERE id=1').get() as {data:string}|undefined; return row?{...defaults(),...JSON.parse(row.data)}:defaults(); }
export async function saveSettings(input:Partial<Settings>){ const next={...(await getSettings()),...input}; db.prepare('INSERT INTO settings(id,data) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(JSON.stringify(next)); return next; }
export function saveScan(scan:ScanResult){ db.prepare('INSERT INTO scans(path,fingerprint,decision,reason,data,scanned_at) VALUES(?,?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET decision=excluded.decision,reason=excluded.reason,data=excluded.data,scanned_at=excluded.scanned_at').run(scan.path,scan.fingerprint,scan.decision,scan.reason,JSON.stringify(scan),scan.scannedAt); db.prepare('INSERT INTO events(type,detail,created_at) VALUES(?,?,?)').run('scan',`${scan.decision}: ${scan.path}`,scan.scannedAt); }
export function listScans(){return (db.prepare('SELECT data FROM scans ORDER BY scanned_at DESC LIMIT 200').all() as {data:string}[]).map(x=>JSON.parse(x.data) as ScanResult);}
export function stats(){return db.prepare("SELECT COUNT(*) total, SUM(decision='pass') pass, SUM(decision='fail') fail, SUM(decision='needs-analysis') analysis FROM scans").get() as {total:number;pass:number;fail:number;analysis:number};}
export function logEvent(type:string,detail:string){db.prepare('INSERT INTO events(type,detail,created_at) VALUES(?,?,?)').run(type,detail,new Date().toISOString());}
export function recentEvents(){return db.prepare('SELECT * FROM events ORDER BY id DESC LIMIT 20').all() as {type:string;detail:string;created_at:string}[];}
export function recordRejection(identity:string,limit:number){const prior=db.prepare('SELECT attempts FROM rejections WHERE identity=?').get(identity) as {attempts:number}|undefined; const attempts=(prior?.attempts||0)+1;db.prepare('INSERT INTO rejections(identity,attempts,updated_at) VALUES(?,?,?) ON CONFLICT(identity) DO UPDATE SET attempts=excluded.attempts,updated_at=excluded.updated_at').run(identity,attempts,new Date().toISOString());return {attempts,needsAttention:attempts>=limit};}
